version: '3'

services:
  db:
    image: mysql:8
    container_name: titan_dev_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: titan
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Seoul'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./ddl:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306